theme = "catppuccin_mocha"
# [theme]
# dark = "catppuccin_mocha"
# light = "catppuccin_latte"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
x = "select_line_below"
X = "select_line_above"

"C-j" = ["half_page_down", "goto_window_center"]
"C-k" = ["half_page_up", "goto_window_center"]

C-y = [
    ':sh rm -f /tmp/unique-file',
    ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
    ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
    ':open %sh{cat /tmp/unique-file}',
    ':redraw',
]

C-s = [
    ":write-all",
    ":insert-output scooter --no-stdin > /dev/tty",
    ":redraw",
    ":reload-all"
]

C-g = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]

C-d = [
    ":write-all",
    ":new",
    ":insert-output lazydocker",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]
