connections:
  pg:
    protocol: postgresql
    username: local
    password: local
    hostname: localhost
    port: 5432
    database: local
  mysql:
    protocol: mysql
    username: local
    password: local
    hostname: localhost
    port: 3306
    database: local
