[settings]
experimental = true
color_theme = "catppuccin"
idiomatic_version_file_enable_tools = ["python", "node"]
trusted_config_paths = ["~/Documents/Projects", "/workspaces"]
lockfile = true

[settings.npm]
package_manager = "bun"

[settings.python]
uv_venv_auto = true

[env]
MISE_GITHUB_TOKEN = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhblByQWUyQzdhalRYSVVBclcreEowS1VhbjdUbHIvNUN4Q2liZnhiSmhVClM4ZGZXQm1aWkFIRlRwQUZ6N2NBaDl5RXVSZndvdDM1cmV4VmQ3Y0Jubm8KLT4gc3NoLWVkMjU1MTkgaytYQ0RnIGNDTnRMMm9scnphSjZEbktqellBOWhvOGZpUVBRTS9BQTRTZy9JYnZEbHMKNVNiMTQ0ZndjSUdXRWh5dGFSK003dTZTZUNibnJZcUJGa2cxZUhtWDJ4VQotPiB3WW4+LWdyZWFzZSAqIjZWRWNdIHI+VTxDSSxoCjRNWFRwMGtJcWpIVVJlTk5NeHE5VDZMMUhkcHhiVWJXU3gwczRPQTA3WUV0WUlpd011S253cHZGZDYzalQxTmsKSUdueGZnCi0tLSAyWXVqNktxWll2RVJiTkJFemg3bzMxbVBsS1BuNG8rVWM0Vk43MUpNaUxjCn9flMcm8Rxd3E7gJtxbfwTxS7In2SwcLPhbK3WDVG0xFkgc8jYBsz2b78YyQIk7N96JkXQLm61WuY38aysrSqWFZdLxGv5KYA" }
