[settings]
experimental = true

[env]
SHELL = "fish"
EDITOR = "hx"
MISE_AGE_KEY = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOW8rM3RwSjhsWVFXZldQY2pVWnRTdGVmM1NHQ0xvaTFtNHVMMUF1WWdVClphN0Jvck1XZjdiY3N6KzgzKzA1cnAyVzBjM2NZL3NCaDU3NEphek1MMFEKLT4gc3NoLWVkMjU1MTkgaytYQ0RnIEo1cFBEVVlob1dOQkN2VUthMEJyRmtZalBhVjZHT0VLdldIemR6QTNNVDAKQkVQd1FvWkxzSXdMaEtHYmg3cm1yaU81aE1xTFc4ZmpoaVRXNlBmL3ZDOAotPiAhLWdyZWFzZSBoYVEgZ1hsWnZbamEgVnxFNAprMkFaT3h4M2o5L3ZEMFdLZHY0TXU5NDhOaUVlYjE2MzJUcwotLS0gRXRCcXhDTnlRVnM2MDlQS1dIQktYR2Z5Tko5TGlJNm9DWml5T1A0bEJRTQpaME5m5x+myDencHsVxMDKEbhxvMT3StQghqsEIHkyvisf/09+7VgTo3gaAzle8LtKzhg0p69xAu8PbtkbPtaEdYhsa/Cs7Ap0UfTpIGiF7eehgfUvT9HZmu3VBKfegJOi4shvi5tnT2eX" }
GITHUB_TOKEN = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYWVNMEw5Y1cxQVEybnBrakx6SElqRnhMenU5M2pGYVZJRUtvcEJIYzBBCmtnWkp0azhwTUJVRHl1cmR5Qks2cmNudHVoZTlQWlFETjJFeGFLaDN4Q00KLT4gc3NoLWVkMjU1MTkgaytYQ0RnIGJPUmRET3JSL0oySy9qYVk4VnpFelNXTld4R0g5U2hDbTNGUkJVZFJ0UWcKeERoa2xqM1hieGdmNEkxNC9wazdlZEduS0IxdDhlenhXTFpoVE94cUVKZwotPiB9UTd2aC1ncmVhc2UgQUtpeW8KQ1lyYlEzeWZ2VDVNUFQ3aGtFMFB2TU8rcy9XRU9TUWZBWC9DcFNNQ3BRCi0tLSA5OUZQWmZ2eXVFSFNOd09XR3VxWi9XSWpQc3F4VEdXMzhlMEt4NEczcU9nCgHiXyi+54dJqkYUbwr5/uI8Nt0TB302ggGQCmC8eSH4SXXLsxyNhHc63Pal7n9nz73OyrT2YCOYI231oyX+l25zuDTQN5eN7g" }

[shell_alias]
cm = "chezmoi"
y = "yazi"
lg = "lazygit"
ld = "lazydocker"
dc = "docker compose"

[tools]
atuin = "latest"
chezmoi = "latest"
fzf = "latest"
helix = "latest"
lazygit = "latest"
starship = "latest"
yazi = "latest"
zoxide = "latest"
